export const  date= [
    {
        name:'领导驾驶舱',
        imgUrl:'ios-paper',
        isSubShow:false,
        path:'/home',
        subItems:[]
    },
    {
        name:'生产计划管理',
        imgUrl:'md-bookmarks',
        isSubShow:false,
        path:'/production',
        subItems:[
            {
                name:'生产计划维护',
                path:'/production',
                isshw:false
            },
            {
                name:'生产计划历史',
                path:'/production/productionhistory',
                isshw:false
            },
        ]
    },
   
    {
        name:'养殖操作',
        imgUrl:'md-pint',
        isSubShow:false,
        path:'/modelcommon/cultivation',
        subItems:[]
    },
    {
        name:'订单管理',
        imgUrl:'md-photos',
        isSubShow:false,
        path:'/modelcommon/orderform',
        subItems:[]
    },
    {
        name:'捕捞记录',
        imgUrl:'ios-person',
        isSubShow:false,
        path:'/modelcommon/catchs',
        subItems:[]
    },
    {
        name:'朔源管理',
        imgUrl:'md-list-box',
        isSubShow:false,
        path:'/source',
        subItems:[
            {
                name:'打印朔源码',
                path:'/source/sourcecode',
                isshw:false
            },
            {
                name:'打印朔管理',
                path:'/source/sourcemanag',
                isshw:false
            },
        ]
    },
    {
        name:'物联网管理',
        imgUrl:'md-link',
        isSubShow:false,
        path:'/internetOfThings',
        subItems:[
            {
                name:'实时监控',
                path:'/',
                isshw:false
            },
            {
                name:'历史数据',
                path:'/internetOfThings/historyDataIndex',
                isshw:false
            },
            {
                name:'图片视频',
                path:'/internetOfThings/picturevideo',
                isshw:false
            },
        ]
    },
    {
        name:'检验检测',
        imgUrl:'md-map',
        isSubShow:false,
        path:'/modelcommon/detection',
        subItems:[]
    },
    {
        name:'销售管理',
        imgUrl:'md-cart ',
        isSubShow:false,
        path:'/modelcommon/market',
        subItems:[]
    },
    {
        name:'售后管理',
        imgUrl:'md-at',
        isSubShow:false,
        path:'/modelcommon/aftersale',
        subItems:[]
    },
    {
        name:'客户管理',
        imgUrl:'md-people',
        isSubShow:false,
        path:'/modelcommon/client',
        subItems:[]
    },
    {
        name:'统计分析',
        imgUrl:'md-podium',
        isSubShow:false,
        path:'/9999',
        subItems:[
            {
                name:'说源码统计',
                path:'/',
                isshw:false
            },
            {
                name:'投入品统计',
                path:'/',
                isshw:false
            },
            {
                name:'检验检测统计',
                path:'/',
                isshw:false
            },
            {
                name:'销售统计',
                path:'/',
                isshw:false
            },
        ]
    },
    {
        name:'基础信息维护',
        imgUrl:'md-menu',
        isSubShow:false,
        path:'/basicmessage',
        subItems:[
            {
                name:'企业信息',
                path:'/basicmessage/eInformation',
                isshw:false
            },
            {
                name:'养殖基地',
                path:'/basicmessage/breedingbase',
                isshw:false
            },
            {
                name:'产品管理',
                path:'/basicmessage/product',
                isshw:false
            },
            {
                name:'投入品管理',
                path:'/basicmessage/ontheproduct',
                isshw:false
            },
            {
                name:'投入品分类',
                path:'/basicmessage/inClassification',
                isshw:false
            },
            {
                name:'产品分类',
                path:'/basicmessage/productClassify',
                isshw:false
            },
            {
                name:'生育期分类',
                path:'/basicmessage/birthCategory',
                isshw:false
            },
            {
                name:'农事操作分类',
                path:'/basicmessage/breedCategory',
                isshw:false
            },
        ]
    },
    {
        name:'系统管理',
        imgUrl:'md-settings',
        isSubShow:false,
        path:'/systemmanagement',
        subItems:[
            {
                name:'组织机构',
                path:'/systemmanagement/managers',
                isshw:false
            },
            {
                name:'用户管理',
                path:'/systemmanagement/usermeages',
                isshw:false
            },
            {
                name:'角色管理',
                path:'/systemmanagement/role',
                isshw:false
            },
            {
                name:'数据字典',
                path:'/systemmanagement/dictionary',
                isshw:false
            },
            {
                name:'病虫害预警设置',
                path:'/systemmanagement/pests',
                isshw:false
            },
            {
                name:'传感器预警设置',
                path:'/systemmanagement/sensor',
                isshw:false
            },
            {
                name:'登陆日志',
                path:'/systemmanagement/loginlog',
                isshw:false
            },
            {
                name:'操作日志',
                path:'/systemmanagement/operationlog',
                isshw:false
            },
        ]
    },
    




]