export const  date= [
    {
        name:'领导驾驶舱',
        imgUrl:'ios-paper',
        isSubShow:false,
        path:'/home',
        subItems:[]
    },
    {
        name:'生产计划管理',
        imgUrl:'md-bookmarks',
        isSubShow:false,
        path:'/production',
        subItems:[
            {
                name:'生产计划维护',
                path:'/production',
                isshw:false
            },
            {
                name:'生产计划历史',
                path:'/production/productionhistory',
                isshw:false
            },
        ]
    },
   
    {
        name:'养殖操作',
        imgUrl:'md-pint',
        isSubShow:false,
        path:'/ewewe',
        subItems:[]
    },
    {
        name:'订单管理',
        imgUrl:'md-photos',
        isSubShow:false,
        path:'/222',
        subItems:[]
    },
    {
        name:'捕捞记录',
        imgUrl:'ios-person',
        isSubShow:false,
        path:'/222',
        subItems:[]
    },
    {
        name:'朔源管理',
        imgUrl:'md-list-box',
        isSubShow:false,
        path:'/9999',
        subItems:[
            {
                name:'打印朔源码',
                path:'/',
                isshw:false
            },
            {
                name:'打印朔管理',
                path:'/',
                isshw:false
            },
        ]
    },
    {
        name:'物联网管理',
        imgUrl:'md-link',
        isSubShow:false,
        path:'/9999',
        subItems:[
            {
                name:'实时监控',
                path:'/',
                isshw:false
            },
            {
                name:'历史数据',
                path:'/',
                isshw:false
            },
            {
                name:'图片视频',
                path:'/',
                isshw:false
            },
        ]
    },
    {
        name:'检验检测',
        imgUrl:'md-map',
        isSubShow:false,
        path:'/9999',
        subItems:[]
    },
    {
        name:'销售管理',
        imgUrl:'md-cart ',
        isSubShow:false,
        path:'/9999',
        subItems:[]
    },
    {
        name:'售后管理',
        imgUrl:'md-at',
        isSubShow:false,
        path:'/9999',
        subItems:[]
    },
    {
        name:'客户管理',
        imgUrl:'md-people',
        isSubShow:false,
        path:'/9999',
        subItems:[]
    },
    {
        name:'统计分析',
        imgUrl:'md-podium',
        isSubShow:false,
        path:'/9999',
        subItems:[
            {
                name:'说源码统计',
                path:'/',
                isshw:false
            },
            {
                name:'投入品统计',
                path:'/',
                isshw:false
            },
            {
                name:'检验检测统计',
                path:'/',
                isshw:false
            },
            {
                name:'销售统计',
                path:'/',
                isshw:false
            },
        ]
    },
    {
        name:'基础信息伟华',
        imgUrl:'md-menu',
        isSubShow:false,
        path:'/9999',
        subItems:[
            {
                name:'企业信息',
                path:'/',
                isshw:false
            },
            {
                name:'养殖基地',
                path:'/',
                isshw:false
            },
            {
                name:'产品管理',
                path:'/',
                isshw:false
            },
            {
                name:'投入品管理',
                path:'/',
                isshw:false
            },
            {
                name:'投入品分类',
                path:'/',
                isshw:false
            },
            {
                name:'产品分类',
                path:'/',
                isshw:false
            },
            {
                name:'生育期分类',
                path:'/',
                isshw:false
            },
            {
                name:'农事操作分类',
                path:'/',
                isshw:false
            },
        ]
    },
    {
        name:'系统管理',
        imgUrl:'md-settings',
        isSubShow:false,
        path:'/9999',
        subItems:[
            {
                name:'组织机构',
                path:'/',
                isshw:false
            },
            {
                name:'用户管理',
                path:'/',
                isshw:false
            },
            {
                name:'角色管理',
                path:'/',
                isshw:false
            },
            {
                name:'数据字典',
                path:'/',
                isshw:false
            },
            {
                name:'病虫害预警设置',
                path:'/',
                isshw:false
            },
            {
                name:'传感器预警设置',
                path:'/',
                isshw:false
            },
            {
                name:'登陆日志',
                path:'/',
                isshw:false
            },
            {
                name:'操作日志',
                path:'/',
                isshw:false
            },
        ]
    },
    




]